/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acces_aiousb_Counter */

#ifndef _Included_com_acces_aiousb_Counter
#define _Included_com_acces_aiousb_Counter
#ifdef __cplusplus
extern "C" {
#endif
#undef com_acces_aiousb_Counter_MODE_TERMINAL_COUNT
#define com_acces_aiousb_Counter_MODE_TERMINAL_COUNT 0L
#undef com_acces_aiousb_Counter_MODE_ONE_SHOT
#define com_acces_aiousb_Counter_MODE_ONE_SHOT 1L
#undef com_acces_aiousb_Counter_MODE_RATE_GENERATOR
#define com_acces_aiousb_Counter_MODE_RATE_GENERATOR 2L
#undef com_acces_aiousb_Counter_MODE_SQUARE_WAVE
#define com_acces_aiousb_Counter_MODE_SQUARE_WAVE 3L
#undef com_acces_aiousb_Counter_MODE_SW_TRIGGERED
#define com_acces_aiousb_Counter_MODE_SW_TRIGGERED 4L
#undef com_acces_aiousb_Counter_MODE_HW_TRIGGERED
#define com_acces_aiousb_Counter_MODE_HW_TRIGGERED 5L
/*
 * Class:     com_acces_aiousb_Counter
 * Method:    setMode
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_Counter_setMode
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_acces_aiousb_Counter
 * Method:    setCount
 * Signature: (IIIC)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_Counter_setCount
  (JNIEnv *, jobject, jint, jint, jint, jchar);

/*
 * Class:     com_acces_aiousb_Counter
 * Method:    setModeAndCount
 * Signature: (IIIIC)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_Counter_setModeAndCount
  (JNIEnv *, jobject, jint, jint, jint, jint, jchar);

/*
 * Class:     com_acces_aiousb_Counter
 * Method:    readCount
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_Counter_readCount
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     com_acces_aiousb_Counter
 * Method:    readCountAndStatus
 * Signature: (III[C)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_Counter_readCountAndStatus
  (JNIEnv *, jobject, jint, jint, jint, jcharArray);

/*
 * Class:     com_acces_aiousb_Counter
 * Method:    readCountAndSetModeAndCount
 * Signature: (IIIIC[C)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_Counter_readCountAndSetModeAndCount
  (JNIEnv *, jobject, jint, jint, jint, jint, jchar, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
