/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acces_aiousb_AO16_AnalogOutputSubsystem */

#ifndef _Included_com_acces_aiousb_AO16_AnalogOutputSubsystem
#define _Included_com_acces_aiousb_AO16_AnalogOutputSubsystem
#ifdef __cplusplus
extern "C" {
#endif
#undef com_acces_aiousb_AO16_AnalogOutputSubsystem_RANGE_0_5V
#define com_acces_aiousb_AO16_AnalogOutputSubsystem_RANGE_0_5V 0L
#undef com_acces_aiousb_AO16_AnalogOutputSubsystem_RANGE_5V
#define com_acces_aiousb_AO16_AnalogOutputSubsystem_RANGE_5V 1L
#undef com_acces_aiousb_AO16_AnalogOutputSubsystem_RANGE_0_10V
#define com_acces_aiousb_AO16_AnalogOutputSubsystem_RANGE_0_10V 2L
#undef com_acces_aiousb_AO16_AnalogOutputSubsystem_RANGE_10V
#define com_acces_aiousb_AO16_AnalogOutputSubsystem_RANGE_10V 3L
#undef com_acces_aiousb_AO16_AnalogOutputSubsystem_MIN_COUNTS
#define com_acces_aiousb_AO16_AnalogOutputSubsystem_MIN_COUNTS 0L
#undef com_acces_aiousb_AO16_AnalogOutputSubsystem_MAX_COUNTS
#define com_acces_aiousb_AO16_AnalogOutputSubsystem_MAX_COUNTS 65535L
/*
 * Class:     com_acces_aiousb_AO16_AnalogOutputSubsystem
 * Method:    setBoardRange
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_AO16_1AnalogOutputSubsystem_setBoardRange
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
