/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acces_aiousb_AnalogInputSubsystem_InputRange */

#ifndef _Included_com_acces_aiousb_AnalogInputSubsystem_InputRange
#define _Included_com_acces_aiousb_AnalogInputSubsystem_InputRange
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
