/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acces_aiousb_USBDevice */

#ifndef _Included_com_acces_aiousb_USBDevice
#define _Included_com_acces_aiousb_USBDevice
#ifdef __cplusplus
extern "C" {
#endif
#undef com_acces_aiousb_USBDevice_CUSTOM_EEPROM_SIZE
#define com_acces_aiousb_USBDevice_CUSTOM_EEPROM_SIZE 512L
#undef com_acces_aiousb_USBDevice_CLEAR_FIFO_METHOD_IMMEDIATE
#define com_acces_aiousb_USBDevice_CLEAR_FIFO_METHOD_IMMEDIATE 0L
#undef com_acces_aiousb_USBDevice_CLEAR_FIFO_METHOD_AUTO
#define com_acces_aiousb_USBDevice_CLEAR_FIFO_METHOD_AUTO 1L
#undef com_acces_aiousb_USBDevice_CLEAR_FIFO_METHOD_IMMEDIATE_AND_ABORT
#define com_acces_aiousb_USBDevice_CLEAR_FIFO_METHOD_IMMEDIATE_AND_ABORT 5L
#undef com_acces_aiousb_USBDevice_CLEAR_FIFO_METHOD_WAIT
#define com_acces_aiousb_USBDevice_CLEAR_FIFO_METHOD_WAIT 86L
/*
 * Class:     com_acces_aiousb_USBDevice
 * Method:    getName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_acces_aiousb_USBDevice_getName
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_acces_aiousb_USBDevice
 * Method:    getDeviceSerialNumber
 * Signature: (I[J)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_USBDevice_getDeviceSerialNumber
  (JNIEnv *, jobject, jint, jlongArray);

/*
 * Class:     com_acces_aiousb_USBDevice
 * Method:    getCommTimeout
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_USBDevice_getCommTimeout
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_acces_aiousb_USBDevice
 * Method:    setCommTimeout
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_USBDevice_setCommTimeout
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_acces_aiousb_USBDevice
 * Method:    reset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_USBDevice_reset
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_acces_aiousb_USBDevice
 * Method:    customEEPROMWrite
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_USBDevice_customEEPROMWrite
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     com_acces_aiousb_USBDevice
 * Method:    customEEPROMRead
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_USBDevice_customEEPROMRead
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     com_acces_aiousb_USBDevice
 * Method:    clearFIFO
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_USBDevice_clearFIFO
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_acces_aiousb_USBDevice
 * Method:    getMiscClock
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_acces_aiousb_USBDevice_getMiscClock
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_acces_aiousb_USBDevice
 * Method:    setMiscClock
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_USBDevice_setMiscClock
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_acces_aiousb_USBDevice
 * Method:    getStreamingBlockSize
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_USBDevice_getStreamingBlockSize
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     com_acces_aiousb_USBDevice
 * Method:    setStreamingBlockSize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_USBDevice_setStreamingBlockSize
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
