/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acces_aiousb_AnalogOutputSubsystem */

#ifndef _Included_com_acces_aiousb_AnalogOutputSubsystem
#define _Included_com_acces_aiousb_AnalogOutputSubsystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_acces_aiousb_AnalogOutputSubsystem
 * Method:    getNumChannels
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_AnalogOutputSubsystem_getNumChannels
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_acces_aiousb_AnalogOutputSubsystem
 * Method:    writeCounts
 * Signature: (IIC)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_AnalogOutputSubsystem_writeCounts__IIC
  (JNIEnv *, jobject, jint, jint, jchar);

/*
 * Class:     com_acces_aiousb_AnalogOutputSubsystem
 * Method:    writeCounts
 * Signature: (I[C)I
 */
JNIEXPORT jint JNICALL Java_com_acces_aiousb_AnalogOutputSubsystem_writeCounts__I_3C
  (JNIEnv *, jobject, jint, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
