/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acces_aiousb_AO16_AnalogOutputSubsystem_OutputRange */

#ifndef _Included_com_acces_aiousb_AO16_AnalogOutputSubsystem_OutputRange
#define _Included_com_acces_aiousb_AO16_AnalogOutputSubsystem_OutputRange
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
